name: Dev Release

on:
  workflow_dispatch:
  schedule:
    - cron : '0 0 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if there are any new commits
        id: check-new-commits
        uses: adriangl/check-new-commits-action@v1.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          seconds: 86400
          branch: 'dev-Tomcat'
  release:
    runs-on: windows-latest
    needs: check
    if: ${{ jobs.check.outputs.has-new-commits == 'true' }}
    steps:
        - name: Fetch merged PRs
          if: ${{ steps.check_commits.outputs.has-new-commits == 'true' }}
          run: |
            echo "Recent merged PRs/commits:" > merged_prs.txt
            git log --merges --pretty=format:"- %s by @%an" -n ${{ steps.check_commits.outputs.new-commits-number }} >> merged_prs.txt
          shell: bash
        - name: Install Arma 3 Tools
          uses: arma-actions/arma3-tools@master
          with:
            toolsUrl: ${{ secrets.ARMA3_TOOLS_URL }}
        - name: Checkout the source code
          uses: actions/checkout@v4
        - name: Setup HEMTT
          uses: arma-actions/hemtt@v1
        - name: Run HEMTT release
          run: hemtt release
        - name: Rename release folder
          run: mv .hemttout/release .hemttout/@kat
        - name: Update to Steam Workshop (dev)
          uses: arma-actions/workshop-upload@v1
          with:
            itemId: '2841189207'
            contentPath: '.hemttout/@kat'
            changelog: |
              Merged Pull Requests:
              $(cat merged_prs.txt)
          env:
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
