name: Dev Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs every midnight UTC

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      has-new-commits: ${{ steps.check-new-commits.outputs.has-new-commits }}
      new-commits-number: ${{ steps.check-new-commits.outputs.new-commits-number }}
    steps:
      - name: Check if there are any new commits
        id: check-new-commits
        uses: adriangl/check-new-commits-action@v1.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          seconds: 86400
          branch: 'dev-Tomcat'

  release:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.has-new-commits == 'true'
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Fetch merged PRs
        run: |
          echo "MERGED_PRS<<;" >> $GITHUB_ENV
          git log --pretty=format:"%s by %an;" -n ${{ needs.check.outputs.new-commits-number }} --no-merges >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        shell: bash

      - name: Install Arma 3 Tools
        uses: arma-actions/arma3-tools@master
        with:
          toolsUrl: ${{ secrets.ARMA3_TOOLS_URL }}

      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1

      - name: Run HEMTT release
        run: hemtt release

      - name: Rename release folder
        run: mv .hemttout/release .hemttout/@kat

      - name: Update to Steam Workshop (dev)
        uses: arma-actions/workshop-upload@v1
        with:
          itemId: '2841189207'
          contentPath: '.hemttout/@kat'
          changelog: ${{ env.MERGED_PRS }}
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
